namespace ModifiersOverhaul.Assets.CharmsModule;

public enum CharmName
{
    NotInitialized = 0,
    WhisperingBreeze = 1,
    DappledLeaf = 2,
    GlimmeringPebble = 3,
    FadedStar = 4,
    GentleWave = 5,
    RustyKey = 6,
    HiddenBlossom = 7,
    ShimmeringDewdrop = 8,
    WanderingCloud = 9,
    DustyJournal = 10,

    CelestialVeil = 11,
    MoonlitSerpent = 12,
    CrystalPrism = 13,
    EmberedFeather = 14,
    EchoingLaughter = 15,
    StarlitCompass = 16,
    MysticLantern = 17,
    ChasingShadows = 18,
    TimelessHourglass = 19,
    EnchantedQuill = 20,

    PhoenixTear = 21,
    SeraphicHalo = 22,
    FrostfireShard = 23,
    WhisperingPhantom = 24,
    CelestialWhirlwind = 25,
    RadiantTear = 26,
    EtherealEcho = 27,
    InfiniteCascade = 28,
    ShatteredDream = 29,
    LuminousHeart = 30,

    DragonsHeart = 31,
    EternalFlame = 32,
    VortexOfTime = 33,
    CelestialCrown = 34,
    ArcaneObelisk = 35,
    StarlightEssence = 36,
    ChosenRelic = 37,
    ShadowedGuardian = 38,
    ElementalSigil = 39,
    CelestialConvergence = 40,

    EldritchMirror = 41,
    PhoenixWing = 42,
    SoulboundEssence = 43,
    AstralNexus = 44,
    WhisperingInfinity = 45,
    ForbiddenTome = 46,
    EtherealBlossom = 47,
    HeartOfTheCosmos = 48,
    DreamweaversThread = 49,
    CelestialSymphony = 50,
}